# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extension.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'extension.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import growtopia_pb2 as growtopia__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xtension.proto\x12\x16gtools.proxy.extension\x1a\x0fgrowtopia.proto\"\x98\x05\n\x06Packet\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.gtools.proxy.extension.Packet.Type\x12\x36\n\thandshake\x18\x02 \x01(\x0b\x32!.gtools.proxy.extension.HandshakeH\x00\x12G\n\x12\x63\x61pability_request\x18\x03 \x01(\x0b\x32).gtools.proxy.extension.CapabilityRequestH\x00\x12I\n\x13\x63\x61pability_response\x18\x04 \x01(\x0b\x32*.gtools.proxy.extension.CapabilityResponseH\x00\x12\x38\n\ndisconnect\x18\x05 \x01(\x0b\x32\".gtools.proxy.extension.DisconnectH\x00\x12.\n\x05\x65vent\x18\x06 \x01(\x0b\x32\x1d.gtools.proxy.extension.EventH\x00\x12\x32\n\x07\x66orward\x18\x07 \x01(\x0b\x32\x1f.gtools.proxy.extension.ForwardH\x00\x12\x30\n\x06\x63\x61ncel\x18\x08 \x01(\x0b\x32\x1e.gtools.proxy.extension.CancelH\x00\"\xb3\x01\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eTYPE_HANDSHAKE\x10\x01\x12\x1b\n\x17TYPE_CAPABILITY_REQUEST\x10\x02\x12\x1c\n\x18TYPE_CAPABILITY_RESPONSE\x10\x03\x12\x13\n\x0fTYPE_DISCONNECT\x10\x04\x12\x0e\n\nTYPE_EVENT\x10\x05\x12\x10\n\x0cTYPE_FORWARD\x10\x06\x12\x0f\n\x0bTYPE_CANCEL\x10\x07\x42\t\n\x07payload\"\x19\n\tHandshake\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x13\n\x11\x43\x61pabilityRequest\"z\n\x12\x43\x61pabilityResponse\x12\x36\n\ncapability\x18\x01 \x03(\x0e\x32\".gtools.proxy.extension.Capability\x12,\n\x08interest\x18\x02 \x03(\x0b\x32\x1a.gtools.growtopia.Interest\"\x0c\n\nDisconnect\"\x07\n\x05\x45vent\"\t\n\x07\x46orward\"\x08\n\x06\x43\x61ncel*m\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\x15\n\x11\x43\x41PABILITY_MODIFY\x10\x01\x12\x15\n\x11\x43\x41PABILITY_CANCEL\x10\x02\x12\x15\n\x11\x43\x41PABILITY_LISTEN\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extension_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITY']._serialized_start=943
  _globals['_CAPABILITY']._serialized_end=1052
  _globals['_PACKET']._serialized_start=61
  _globals['_PACKET']._serialized_end=725
  _globals['_PACKET_TYPE']._serialized_start=535
  _globals['_PACKET_TYPE']._serialized_end=714
  _globals['_HANDSHAKE']._serialized_start=727
  _globals['_HANDSHAKE']._serialized_end=752
  _globals['_CAPABILITYREQUEST']._serialized_start=754
  _globals['_CAPABILITYREQUEST']._serialized_end=773
  _globals['_CAPABILITYRESPONSE']._serialized_start=775
  _globals['_CAPABILITYRESPONSE']._serialized_end=897
  _globals['_DISCONNECT']._serialized_start=899
  _globals['_DISCONNECT']._serialized_end=911
  _globals['_EVENT']._serialized_start=913
  _globals['_EVENT']._serialized_end=920
  _globals['_FORWARD']._serialized_start=922
  _globals['_FORWARD']._serialized_end=931
  _globals['_CANCEL']._serialized_start=933
  _globals['_CANCEL']._serialized_end=941
# @@protoc_insertion_point(module_scope)
