# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: strkv.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'strkv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstrkv.proto\x12\x12gtools.strkv.query\"\x9e\x01\n\x07\x46indRow\x12\x32\n\x06method\x18\x01 \x01(\x0e\x32\".gtools.strkv.query.FindRow.Method\x12\r\n\x03key\x18\x02 \x01(\x0cH\x00\x12\x0f\n\x05index\x18\x04 \x01(\x05H\x00\":\n\x06Method\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03KEY\x10\x01\x12\x0b\n\x07KEY_ANY\x10\x02\x12\t\n\x05INDEX\x10\x03\x42\x03\n\x01m\"\x83\x01\n\x07\x46indCol\x12\x32\n\x06method\x18\x01 \x01(\x0e\x32\".gtools.strkv.query.FindCol.Method\x12\r\n\x05index\x18\x02 \x01(\x05\"5\n\x06Method\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0c\n\x08\x41\x42SOLUTE\x10\x01\x12\x0c\n\x08RELATIVE\x10\x02\"i\n\x06\x43lause\x12(\n\x03row\x18\x01 \x01(\x0b\x32\x1b.gtools.strkv.query.FindRow\x12-\n\x03\x63ol\x18\x02 \x01(\x0b\x32\x1b.gtools.strkv.query.FindColH\x00\x88\x01\x01\x42\x06\n\x04_col\"2\n\x05Query\x12)\n\x05where\x18\x01 \x03(\x0b\x32\x1a.gtools.strkv.query.Clauseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strkv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINDROW']._serialized_start=36
  _globals['_FINDROW']._serialized_end=194
  _globals['_FINDROW_METHOD']._serialized_start=131
  _globals['_FINDROW_METHOD']._serialized_end=189
  _globals['_FINDCOL']._serialized_start=197
  _globals['_FINDCOL']._serialized_end=328
  _globals['_FINDCOL_METHOD']._serialized_start=275
  _globals['_FINDCOL_METHOD']._serialized_end=328
  _globals['_CLAUSE']._serialized_start=330
  _globals['_CLAUSE']._serialized_end=435
  _globals['_QUERY']._serialized_start=437
  _globals['_QUERY']._serialized_end=487
# @@protoc_insertion_point(module_scope)
