# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: variant.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'variant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvariant.proto\x12\x14gtools.variant.query\"\x1a\n\rVariantClause\x12\t\n\x01v\x18\x01 \x01(\r\"B\n\x0cVariantQuery\x12\x32\n\x05where\x18\x01 \x03(\x0b\x32#.gtools.variant.query.VariantClauseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'variant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VARIANTCLAUSE']._serialized_start=39
  _globals['_VARIANTCLAUSE']._serialized_end=65
  _globals['_VARIANTQUERY']._serialized_start=67
  _globals['_VARIANTQUERY']._serialized_end=133
# @@protoc_insertion_point(module_scope)
