// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: op.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Any } from "./google/protobuf/any";

export const protobufPackage = "gtools.op";

export enum Op {
  OP_UNSPECIFIED = 0,
  OP_EQ = 1,
  OP_EQ_EPS = 2,
  OP_NEQ = 3,
  OP_GT = 4,
  OP_GTE = 5,
  OP_LT = 6,
  OP_LTE = 7,
  OP_BIT_TEST = 8,
  OP_LIKE = 9,
  OP_STARTSWITH = 10,
  OP_ENDSWITH = 11,
  OP_CONTAINS = 12,
  UNRECOGNIZED = -1,
}

export function opFromJSON(object: any): Op {
  switch (object) {
    case 0:
    case "OP_UNSPECIFIED":
      return Op.OP_UNSPECIFIED;
    case 1:
    case "OP_EQ":
      return Op.OP_EQ;
    case 2:
    case "OP_EQ_EPS":
      return Op.OP_EQ_EPS;
    case 3:
    case "OP_NEQ":
      return Op.OP_NEQ;
    case 4:
    case "OP_GT":
      return Op.OP_GT;
    case 5:
    case "OP_GTE":
      return Op.OP_GTE;
    case 6:
    case "OP_LT":
      return Op.OP_LT;
    case 7:
    case "OP_LTE":
      return Op.OP_LTE;
    case 8:
    case "OP_BIT_TEST":
      return Op.OP_BIT_TEST;
    case 9:
    case "OP_LIKE":
      return Op.OP_LIKE;
    case 10:
    case "OP_STARTSWITH":
      return Op.OP_STARTSWITH;
    case 11:
    case "OP_ENDSWITH":
      return Op.OP_ENDSWITH;
    case 12:
    case "OP_CONTAINS":
      return Op.OP_CONTAINS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Op.UNRECOGNIZED;
  }
}

export function opToJSON(object: Op): string {
  switch (object) {
    case Op.OP_UNSPECIFIED:
      return "OP_UNSPECIFIED";
    case Op.OP_EQ:
      return "OP_EQ";
    case Op.OP_EQ_EPS:
      return "OP_EQ_EPS";
    case Op.OP_NEQ:
      return "OP_NEQ";
    case Op.OP_GT:
      return "OP_GT";
    case Op.OP_GTE:
      return "OP_GTE";
    case Op.OP_LT:
      return "OP_LT";
    case Op.OP_LTE:
      return "OP_LTE";
    case Op.OP_BIT_TEST:
      return "OP_BIT_TEST";
    case Op.OP_LIKE:
      return "OP_LIKE";
    case Op.OP_STARTSWITH:
      return "OP_STARTSWITH";
    case Op.OP_ENDSWITH:
      return "OP_ENDSWITH";
    case Op.OP_CONTAINS:
      return "OP_CONTAINS";
    case Op.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Vec2 {
  x: number;
  y: number;
}

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export interface BinOp {
  lvalue: Any | undefined;
  op: Op;
  u32?: number | undefined;
  i32?: number | undefined;
  flt?: number | undefined;
  str?: string | undefined;
  buf?: Uint8Array | undefined;
  vec2?: Vec2 | undefined;
  vec3?: Vec3 | undefined;
}

function createBaseVec2(): Vec2 {
  return { x: 0, y: 0 };
}

export const Vec2: MessageFns<Vec2> = {
  encode(message: Vec2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(13).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(21).float(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Vec2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVec2();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.y = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Vec2 {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: Vec2): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Vec2>, I>>(base?: I): Vec2 {
    return Vec2.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Vec2>, I>>(object: I): Vec2 {
    const message = createBaseVec2();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseVec3(): Vec3 {
  return { x: 0, y: 0, z: 0 };
}

export const Vec3: MessageFns<Vec3> = {
  encode(message: Vec3, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(13).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(21).float(message.y);
    }
    if (message.z !== 0) {
      writer.uint32(29).float(message.z);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Vec3 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVec3();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.y = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.z = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Vec3 {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
    };
  },

  toJSON(message: Vec3): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.z !== 0) {
      obj.z = message.z;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Vec3>, I>>(base?: I): Vec3 {
    return Vec3.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Vec3>, I>>(object: I): Vec3 {
    const message = createBaseVec3();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.z = object.z ?? 0;
    return message;
  },
};

function createBaseBinOp(): BinOp {
  return {
    lvalue: undefined,
    op: 0,
    u32: undefined,
    i32: undefined,
    flt: undefined,
    str: undefined,
    buf: undefined,
    vec2: undefined,
    vec3: undefined,
  };
}

export const BinOp: MessageFns<BinOp> = {
  encode(message: BinOp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lvalue !== undefined) {
      Any.encode(message.lvalue, writer.uint32(10).fork()).join();
    }
    if (message.op !== 0) {
      writer.uint32(24).int32(message.op);
    }
    if (message.u32 !== undefined) {
      writer.uint32(32).uint32(message.u32);
    }
    if (message.i32 !== undefined) {
      writer.uint32(40).int32(message.i32);
    }
    if (message.flt !== undefined) {
      writer.uint32(53).float(message.flt);
    }
    if (message.str !== undefined) {
      writer.uint32(58).string(message.str);
    }
    if (message.buf !== undefined) {
      writer.uint32(66).bytes(message.buf);
    }
    if (message.vec2 !== undefined) {
      Vec2.encode(message.vec2, writer.uint32(82).fork()).join();
    }
    if (message.vec3 !== undefined) {
      Vec3.encode(message.vec3, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BinOp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBinOp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.lvalue = Any.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.op = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.u32 = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.i32 = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.flt = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.str = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.buf = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.vec2 = Vec2.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.vec3 = Vec3.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BinOp {
    return {
      lvalue: isSet(object.lvalue) ? Any.fromJSON(object.lvalue) : undefined,
      op: isSet(object.op) ? opFromJSON(object.op) : 0,
      u32: isSet(object.u32) ? globalThis.Number(object.u32) : undefined,
      i32: isSet(object.i32) ? globalThis.Number(object.i32) : undefined,
      flt: isSet(object.flt) ? globalThis.Number(object.flt) : undefined,
      str: isSet(object.str) ? globalThis.String(object.str) : undefined,
      buf: isSet(object.buf) ? bytesFromBase64(object.buf) : undefined,
      vec2: isSet(object.vec2) ? Vec2.fromJSON(object.vec2) : undefined,
      vec3: isSet(object.vec3) ? Vec3.fromJSON(object.vec3) : undefined,
    };
  },

  toJSON(message: BinOp): unknown {
    const obj: any = {};
    if (message.lvalue !== undefined) {
      obj.lvalue = Any.toJSON(message.lvalue);
    }
    if (message.op !== 0) {
      obj.op = opToJSON(message.op);
    }
    if (message.u32 !== undefined) {
      obj.u32 = Math.round(message.u32);
    }
    if (message.i32 !== undefined) {
      obj.i32 = Math.round(message.i32);
    }
    if (message.flt !== undefined) {
      obj.flt = message.flt;
    }
    if (message.str !== undefined) {
      obj.str = message.str;
    }
    if (message.buf !== undefined) {
      obj.buf = base64FromBytes(message.buf);
    }
    if (message.vec2 !== undefined) {
      obj.vec2 = Vec2.toJSON(message.vec2);
    }
    if (message.vec3 !== undefined) {
      obj.vec3 = Vec3.toJSON(message.vec3);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BinOp>, I>>(base?: I): BinOp {
    return BinOp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BinOp>, I>>(object: I): BinOp {
    const message = createBaseBinOp();
    message.lvalue = (object.lvalue !== undefined && object.lvalue !== null)
      ? Any.fromPartial(object.lvalue)
      : undefined;
    message.op = object.op ?? 0;
    message.u32 = object.u32 ?? undefined;
    message.i32 = object.i32 ?? undefined;
    message.flt = object.flt ?? undefined;
    message.str = object.str ?? undefined;
    message.buf = object.buf ?? undefined;
    message.vec2 = (object.vec2 !== undefined && object.vec2 !== null) ? Vec2.fromPartial(object.vec2) : undefined;
    message.vec3 = (object.vec3 !== undefined && object.vec3 !== null) ? Vec3.fromPartial(object.vec3) : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
