// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: state.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { CharacterState, Inventory, Player, Tile, World } from "./growtopia";

export const protobufPackage = "gtools.state";

export enum StateUpdateWhat {
  STATE_UNSPECIFIED = 0,
  STATE_PLAYER_UPDATE = 1,
  STATE_SET_MY_PLAYER = 2,
  STATE_SEND_INVENTORY = 3,
  STATE_MODIFY_INVENTORY = 4,
  STATE_ENTER_WORLD = 5,
  STATE_EXIT_WORLD = 6,
  STATE_PLAYER_JOIN = 8,
  STATE_PLAYER_LEAVE = 9,
  STATE_MODIFY_WORLD = 10,
  STATE_MODIFY_ITEM = 11,
  STATE_UPDATE_STATUS = 12,
  STATE_SET_CHARACTER_STATE = 13,
  STATE_SET_MY_TELEMETRY = 14,
  UNRECOGNIZED = -1,
}

export function stateUpdateWhatFromJSON(object: any): StateUpdateWhat {
  switch (object) {
    case 0:
    case "STATE_UNSPECIFIED":
      return StateUpdateWhat.STATE_UNSPECIFIED;
    case 1:
    case "STATE_PLAYER_UPDATE":
      return StateUpdateWhat.STATE_PLAYER_UPDATE;
    case 2:
    case "STATE_SET_MY_PLAYER":
      return StateUpdateWhat.STATE_SET_MY_PLAYER;
    case 3:
    case "STATE_SEND_INVENTORY":
      return StateUpdateWhat.STATE_SEND_INVENTORY;
    case 4:
    case "STATE_MODIFY_INVENTORY":
      return StateUpdateWhat.STATE_MODIFY_INVENTORY;
    case 5:
    case "STATE_ENTER_WORLD":
      return StateUpdateWhat.STATE_ENTER_WORLD;
    case 6:
    case "STATE_EXIT_WORLD":
      return StateUpdateWhat.STATE_EXIT_WORLD;
    case 8:
    case "STATE_PLAYER_JOIN":
      return StateUpdateWhat.STATE_PLAYER_JOIN;
    case 9:
    case "STATE_PLAYER_LEAVE":
      return StateUpdateWhat.STATE_PLAYER_LEAVE;
    case 10:
    case "STATE_MODIFY_WORLD":
      return StateUpdateWhat.STATE_MODIFY_WORLD;
    case 11:
    case "STATE_MODIFY_ITEM":
      return StateUpdateWhat.STATE_MODIFY_ITEM;
    case 12:
    case "STATE_UPDATE_STATUS":
      return StateUpdateWhat.STATE_UPDATE_STATUS;
    case 13:
    case "STATE_SET_CHARACTER_STATE":
      return StateUpdateWhat.STATE_SET_CHARACTER_STATE;
    case 14:
    case "STATE_SET_MY_TELEMETRY":
      return StateUpdateWhat.STATE_SET_MY_TELEMETRY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StateUpdateWhat.UNRECOGNIZED;
  }
}

export function stateUpdateWhatToJSON(object: StateUpdateWhat): string {
  switch (object) {
    case StateUpdateWhat.STATE_UNSPECIFIED:
      return "STATE_UNSPECIFIED";
    case StateUpdateWhat.STATE_PLAYER_UPDATE:
      return "STATE_PLAYER_UPDATE";
    case StateUpdateWhat.STATE_SET_MY_PLAYER:
      return "STATE_SET_MY_PLAYER";
    case StateUpdateWhat.STATE_SEND_INVENTORY:
      return "STATE_SEND_INVENTORY";
    case StateUpdateWhat.STATE_MODIFY_INVENTORY:
      return "STATE_MODIFY_INVENTORY";
    case StateUpdateWhat.STATE_ENTER_WORLD:
      return "STATE_ENTER_WORLD";
    case StateUpdateWhat.STATE_EXIT_WORLD:
      return "STATE_EXIT_WORLD";
    case StateUpdateWhat.STATE_PLAYER_JOIN:
      return "STATE_PLAYER_JOIN";
    case StateUpdateWhat.STATE_PLAYER_LEAVE:
      return "STATE_PLAYER_LEAVE";
    case StateUpdateWhat.STATE_MODIFY_WORLD:
      return "STATE_MODIFY_WORLD";
    case StateUpdateWhat.STATE_MODIFY_ITEM:
      return "STATE_MODIFY_ITEM";
    case StateUpdateWhat.STATE_UPDATE_STATUS:
      return "STATE_UPDATE_STATUS";
    case StateUpdateWhat.STATE_SET_CHARACTER_STATE:
      return "STATE_SET_CHARACTER_STATE";
    case StateUpdateWhat.STATE_SET_MY_TELEMETRY:
      return "STATE_SET_MY_TELEMETRY";
    case StateUpdateWhat.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface StateUpdate {
  what: StateUpdateWhat;
  playerUpdate?: PlayerUpdate | undefined;
  setMyPlayer?: number | undefined;
  sendInventory?: Inventory | undefined;
  modifyInventory?: ModifyInventory | undefined;
  enterWorld?: EnterWorld | undefined;
  playerJoin?: Player | undefined;
  playerLeave?: number | undefined;
  modifyWorld?: ModifyWorld | undefined;
  modifyItem?: ModifyItem | undefined;
  updateStatus?: number | undefined;
  characterState?: CharacterState | undefined;
  setMyTelemetry?: SetMyTelemetry | undefined;
}

export interface ModifyWorld {
  op: ModifyWorld_Op;
  tile: Tile | undefined;
}

export enum ModifyWorld_Op {
  OP_UNSPECIFIED = 0,
  OP_REPLACE = 1,
  OP_PLACE = 2,
  OP_DESTROY = 3,
  UNRECOGNIZED = -1,
}

export function modifyWorld_OpFromJSON(object: any): ModifyWorld_Op {
  switch (object) {
    case 0:
    case "OP_UNSPECIFIED":
      return ModifyWorld_Op.OP_UNSPECIFIED;
    case 1:
    case "OP_REPLACE":
      return ModifyWorld_Op.OP_REPLACE;
    case 2:
    case "OP_PLACE":
      return ModifyWorld_Op.OP_PLACE;
    case 3:
    case "OP_DESTROY":
      return ModifyWorld_Op.OP_DESTROY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ModifyWorld_Op.UNRECOGNIZED;
  }
}

export function modifyWorld_OpToJSON(object: ModifyWorld_Op): string {
  switch (object) {
    case ModifyWorld_Op.OP_UNSPECIFIED:
      return "OP_UNSPECIFIED";
    case ModifyWorld_Op.OP_REPLACE:
      return "OP_REPLACE";
    case ModifyWorld_Op.OP_PLACE:
      return "OP_PLACE";
    case ModifyWorld_Op.OP_DESTROY:
      return "OP_DESTROY";
    case ModifyWorld_Op.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SetMyTelemetry {
  serverPing: number;
  clientPing: number;
  timeSinceLogin: number;
  timeInWorld: number;
}

export interface ModifyItem {
  op: ModifyItem_Op;
  itemId: number;
  uid: number;
  amount: number;
  x: number;
  y: number;
  flags: number;
}

export enum ModifyItem_Op {
  OP_UNSPECIFIED = 0,
  OP_CREATE = 1,
  OP_SET_AMOUNT = 3,
  OP_TAKE = 4,
  UNRECOGNIZED = -1,
}

export function modifyItem_OpFromJSON(object: any): ModifyItem_Op {
  switch (object) {
    case 0:
    case "OP_UNSPECIFIED":
      return ModifyItem_Op.OP_UNSPECIFIED;
    case 1:
    case "OP_CREATE":
      return ModifyItem_Op.OP_CREATE;
    case 3:
    case "OP_SET_AMOUNT":
      return ModifyItem_Op.OP_SET_AMOUNT;
    case 4:
    case "OP_TAKE":
      return ModifyItem_Op.OP_TAKE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ModifyItem_Op.UNRECOGNIZED;
  }
}

export function modifyItem_OpToJSON(object: ModifyItem_Op): string {
  switch (object) {
    case ModifyItem_Op.OP_UNSPECIFIED:
      return "OP_UNSPECIFIED";
    case ModifyItem_Op.OP_CREATE:
      return "OP_CREATE";
    case ModifyItem_Op.OP_SET_AMOUNT:
      return "OP_SET_AMOUNT";
    case ModifyItem_Op.OP_TAKE:
      return "OP_TAKE";
    case ModifyItem_Op.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface EnterWorld {
  enterWorld: World | undefined;
  doorId: Uint8Array;
}

export interface ModifyInventory {
  id: number;
  toAdd: number;
  isGhost: boolean;
}

export interface PlayerUpdate {
  netId: number;
  x: number;
  y: number;
  state: number;
}

function createBaseStateUpdate(): StateUpdate {
  return {
    what: 0,
    playerUpdate: undefined,
    setMyPlayer: undefined,
    sendInventory: undefined,
    modifyInventory: undefined,
    enterWorld: undefined,
    playerJoin: undefined,
    playerLeave: undefined,
    modifyWorld: undefined,
    modifyItem: undefined,
    updateStatus: undefined,
    characterState: undefined,
    setMyTelemetry: undefined,
  };
}

export const StateUpdate: MessageFns<StateUpdate> = {
  encode(message: StateUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.what !== 0) {
      writer.uint32(8).int32(message.what);
    }
    if (message.playerUpdate !== undefined) {
      PlayerUpdate.encode(message.playerUpdate, writer.uint32(18).fork()).join();
    }
    if (message.setMyPlayer !== undefined) {
      writer.uint32(24).uint32(message.setMyPlayer);
    }
    if (message.sendInventory !== undefined) {
      Inventory.encode(message.sendInventory, writer.uint32(34).fork()).join();
    }
    if (message.modifyInventory !== undefined) {
      ModifyInventory.encode(message.modifyInventory, writer.uint32(42).fork()).join();
    }
    if (message.enterWorld !== undefined) {
      EnterWorld.encode(message.enterWorld, writer.uint32(50).fork()).join();
    }
    if (message.playerJoin !== undefined) {
      Player.encode(message.playerJoin, writer.uint32(58).fork()).join();
    }
    if (message.playerLeave !== undefined) {
      writer.uint32(64).uint32(message.playerLeave);
    }
    if (message.modifyWorld !== undefined) {
      ModifyWorld.encode(message.modifyWorld, writer.uint32(106).fork()).join();
    }
    if (message.modifyItem !== undefined) {
      ModifyItem.encode(message.modifyItem, writer.uint32(74).fork()).join();
    }
    if (message.updateStatus !== undefined) {
      writer.uint32(80).uint32(message.updateStatus);
    }
    if (message.characterState !== undefined) {
      CharacterState.encode(message.characterState, writer.uint32(90).fork()).join();
    }
    if (message.setMyTelemetry !== undefined) {
      SetMyTelemetry.encode(message.setMyTelemetry, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.what = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.playerUpdate = PlayerUpdate.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.setMyPlayer = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sendInventory = Inventory.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.modifyInventory = ModifyInventory.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.enterWorld = EnterWorld.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.playerJoin = Player.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.playerLeave = reader.uint32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.modifyWorld = ModifyWorld.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.modifyItem = ModifyItem.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.updateStatus = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.characterState = CharacterState.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.setMyTelemetry = SetMyTelemetry.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateUpdate {
    return {
      what: isSet(object.what) ? stateUpdateWhatFromJSON(object.what) : 0,
      playerUpdate: isSet(object.playerUpdate)
        ? PlayerUpdate.fromJSON(object.playerUpdate)
        : isSet(object.player_update)
        ? PlayerUpdate.fromJSON(object.player_update)
        : undefined,
      setMyPlayer: isSet(object.setMyPlayer)
        ? globalThis.Number(object.setMyPlayer)
        : isSet(object.set_my_player)
        ? globalThis.Number(object.set_my_player)
        : undefined,
      sendInventory: isSet(object.sendInventory)
        ? Inventory.fromJSON(object.sendInventory)
        : isSet(object.send_inventory)
        ? Inventory.fromJSON(object.send_inventory)
        : undefined,
      modifyInventory: isSet(object.modifyInventory)
        ? ModifyInventory.fromJSON(object.modifyInventory)
        : isSet(object.modify_inventory)
        ? ModifyInventory.fromJSON(object.modify_inventory)
        : undefined,
      enterWorld: isSet(object.enterWorld)
        ? EnterWorld.fromJSON(object.enterWorld)
        : isSet(object.enter_world)
        ? EnterWorld.fromJSON(object.enter_world)
        : undefined,
      playerJoin: isSet(object.playerJoin)
        ? Player.fromJSON(object.playerJoin)
        : isSet(object.player_join)
        ? Player.fromJSON(object.player_join)
        : undefined,
      playerLeave: isSet(object.playerLeave)
        ? globalThis.Number(object.playerLeave)
        : isSet(object.player_leave)
        ? globalThis.Number(object.player_leave)
        : undefined,
      modifyWorld: isSet(object.modifyWorld)
        ? ModifyWorld.fromJSON(object.modifyWorld)
        : isSet(object.modify_world)
        ? ModifyWorld.fromJSON(object.modify_world)
        : undefined,
      modifyItem: isSet(object.modifyItem)
        ? ModifyItem.fromJSON(object.modifyItem)
        : isSet(object.modify_item)
        ? ModifyItem.fromJSON(object.modify_item)
        : undefined,
      updateStatus: isSet(object.updateStatus)
        ? globalThis.Number(object.updateStatus)
        : isSet(object.update_status)
        ? globalThis.Number(object.update_status)
        : undefined,
      characterState: isSet(object.characterState)
        ? CharacterState.fromJSON(object.characterState)
        : isSet(object.character_state)
        ? CharacterState.fromJSON(object.character_state)
        : undefined,
      setMyTelemetry: isSet(object.setMyTelemetry)
        ? SetMyTelemetry.fromJSON(object.setMyTelemetry)
        : isSet(object.set_my_telemetry)
        ? SetMyTelemetry.fromJSON(object.set_my_telemetry)
        : undefined,
    };
  },

  toJSON(message: StateUpdate): unknown {
    const obj: any = {};
    if (message.what !== 0) {
      obj.what = stateUpdateWhatToJSON(message.what);
    }
    if (message.playerUpdate !== undefined) {
      obj.playerUpdate = PlayerUpdate.toJSON(message.playerUpdate);
    }
    if (message.setMyPlayer !== undefined) {
      obj.setMyPlayer = Math.round(message.setMyPlayer);
    }
    if (message.sendInventory !== undefined) {
      obj.sendInventory = Inventory.toJSON(message.sendInventory);
    }
    if (message.modifyInventory !== undefined) {
      obj.modifyInventory = ModifyInventory.toJSON(message.modifyInventory);
    }
    if (message.enterWorld !== undefined) {
      obj.enterWorld = EnterWorld.toJSON(message.enterWorld);
    }
    if (message.playerJoin !== undefined) {
      obj.playerJoin = Player.toJSON(message.playerJoin);
    }
    if (message.playerLeave !== undefined) {
      obj.playerLeave = Math.round(message.playerLeave);
    }
    if (message.modifyWorld !== undefined) {
      obj.modifyWorld = ModifyWorld.toJSON(message.modifyWorld);
    }
    if (message.modifyItem !== undefined) {
      obj.modifyItem = ModifyItem.toJSON(message.modifyItem);
    }
    if (message.updateStatus !== undefined) {
      obj.updateStatus = Math.round(message.updateStatus);
    }
    if (message.characterState !== undefined) {
      obj.characterState = CharacterState.toJSON(message.characterState);
    }
    if (message.setMyTelemetry !== undefined) {
      obj.setMyTelemetry = SetMyTelemetry.toJSON(message.setMyTelemetry);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateUpdate>, I>>(base?: I): StateUpdate {
    return StateUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateUpdate>, I>>(object: I): StateUpdate {
    const message = createBaseStateUpdate();
    message.what = object.what ?? 0;
    message.playerUpdate = (object.playerUpdate !== undefined && object.playerUpdate !== null)
      ? PlayerUpdate.fromPartial(object.playerUpdate)
      : undefined;
    message.setMyPlayer = object.setMyPlayer ?? undefined;
    message.sendInventory = (object.sendInventory !== undefined && object.sendInventory !== null)
      ? Inventory.fromPartial(object.sendInventory)
      : undefined;
    message.modifyInventory = (object.modifyInventory !== undefined && object.modifyInventory !== null)
      ? ModifyInventory.fromPartial(object.modifyInventory)
      : undefined;
    message.enterWorld = (object.enterWorld !== undefined && object.enterWorld !== null)
      ? EnterWorld.fromPartial(object.enterWorld)
      : undefined;
    message.playerJoin = (object.playerJoin !== undefined && object.playerJoin !== null)
      ? Player.fromPartial(object.playerJoin)
      : undefined;
    message.playerLeave = object.playerLeave ?? undefined;
    message.modifyWorld = (object.modifyWorld !== undefined && object.modifyWorld !== null)
      ? ModifyWorld.fromPartial(object.modifyWorld)
      : undefined;
    message.modifyItem = (object.modifyItem !== undefined && object.modifyItem !== null)
      ? ModifyItem.fromPartial(object.modifyItem)
      : undefined;
    message.updateStatus = object.updateStatus ?? undefined;
    message.characterState = (object.characterState !== undefined && object.characterState !== null)
      ? CharacterState.fromPartial(object.characterState)
      : undefined;
    message.setMyTelemetry = (object.setMyTelemetry !== undefined && object.setMyTelemetry !== null)
      ? SetMyTelemetry.fromPartial(object.setMyTelemetry)
      : undefined;
    return message;
  },
};

function createBaseModifyWorld(): ModifyWorld {
  return { op: 0, tile: undefined };
}

export const ModifyWorld: MessageFns<ModifyWorld> = {
  encode(message: ModifyWorld, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.op !== 0) {
      writer.uint32(48).int32(message.op);
    }
    if (message.tile !== undefined) {
      Tile.encode(message.tile, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModifyWorld {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModifyWorld();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.op = reader.int32() as any;
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tile = Tile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModifyWorld {
    return {
      op: isSet(object.op) ? modifyWorld_OpFromJSON(object.op) : 0,
      tile: isSet(object.tile) ? Tile.fromJSON(object.tile) : undefined,
    };
  },

  toJSON(message: ModifyWorld): unknown {
    const obj: any = {};
    if (message.op !== 0) {
      obj.op = modifyWorld_OpToJSON(message.op);
    }
    if (message.tile !== undefined) {
      obj.tile = Tile.toJSON(message.tile);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModifyWorld>, I>>(base?: I): ModifyWorld {
    return ModifyWorld.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModifyWorld>, I>>(object: I): ModifyWorld {
    const message = createBaseModifyWorld();
    message.op = object.op ?? 0;
    message.tile = (object.tile !== undefined && object.tile !== null) ? Tile.fromPartial(object.tile) : undefined;
    return message;
  },
};

function createBaseSetMyTelemetry(): SetMyTelemetry {
  return { serverPing: 0, clientPing: 0, timeSinceLogin: 0, timeInWorld: 0 };
}

export const SetMyTelemetry: MessageFns<SetMyTelemetry> = {
  encode(message: SetMyTelemetry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverPing !== 0) {
      writer.uint32(40).uint32(message.serverPing);
    }
    if (message.clientPing !== 0) {
      writer.uint32(64).uint32(message.clientPing);
    }
    if (message.timeSinceLogin !== 0) {
      writer.uint32(53).float(message.timeSinceLogin);
    }
    if (message.timeInWorld !== 0) {
      writer.uint32(61).float(message.timeInWorld);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetMyTelemetry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetMyTelemetry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.serverPing = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.clientPing = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.timeSinceLogin = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.timeInWorld = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetMyTelemetry {
    return {
      serverPing: isSet(object.serverPing)
        ? globalThis.Number(object.serverPing)
        : isSet(object.server_ping)
        ? globalThis.Number(object.server_ping)
        : 0,
      clientPing: isSet(object.clientPing)
        ? globalThis.Number(object.clientPing)
        : isSet(object.client_ping)
        ? globalThis.Number(object.client_ping)
        : 0,
      timeSinceLogin: isSet(object.timeSinceLogin)
        ? globalThis.Number(object.timeSinceLogin)
        : isSet(object.time_since_login)
        ? globalThis.Number(object.time_since_login)
        : 0,
      timeInWorld: isSet(object.timeInWorld)
        ? globalThis.Number(object.timeInWorld)
        : isSet(object.time_in_world)
        ? globalThis.Number(object.time_in_world)
        : 0,
    };
  },

  toJSON(message: SetMyTelemetry): unknown {
    const obj: any = {};
    if (message.serverPing !== 0) {
      obj.serverPing = Math.round(message.serverPing);
    }
    if (message.clientPing !== 0) {
      obj.clientPing = Math.round(message.clientPing);
    }
    if (message.timeSinceLogin !== 0) {
      obj.timeSinceLogin = message.timeSinceLogin;
    }
    if (message.timeInWorld !== 0) {
      obj.timeInWorld = message.timeInWorld;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMyTelemetry>, I>>(base?: I): SetMyTelemetry {
    return SetMyTelemetry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMyTelemetry>, I>>(object: I): SetMyTelemetry {
    const message = createBaseSetMyTelemetry();
    message.serverPing = object.serverPing ?? 0;
    message.clientPing = object.clientPing ?? 0;
    message.timeSinceLogin = object.timeSinceLogin ?? 0;
    message.timeInWorld = object.timeInWorld ?? 0;
    return message;
  },
};

function createBaseModifyItem(): ModifyItem {
  return { op: 0, itemId: 0, uid: 0, amount: 0, x: 0, y: 0, flags: 0 };
}

export const ModifyItem: MessageFns<ModifyItem> = {
  encode(message: ModifyItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.op !== 0) {
      writer.uint32(8).int32(message.op);
    }
    if (message.itemId !== 0) {
      writer.uint32(16).uint32(message.itemId);
    }
    if (message.uid !== 0) {
      writer.uint32(24).uint32(message.uid);
    }
    if (message.amount !== 0) {
      writer.uint32(48).uint32(message.amount);
    }
    if (message.x !== 0) {
      writer.uint32(37).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(45).float(message.y);
    }
    if (message.flags !== 0) {
      writer.uint32(56).uint32(message.flags);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModifyItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModifyItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.op = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.itemId = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.uid = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.amount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.y = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.flags = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModifyItem {
    return {
      op: isSet(object.op) ? modifyItem_OpFromJSON(object.op) : 0,
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
        ? globalThis.Number(object.item_id)
        : 0,
      uid: isSet(object.uid) ? globalThis.Number(object.uid) : 0,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      flags: isSet(object.flags) ? globalThis.Number(object.flags) : 0,
    };
  },

  toJSON(message: ModifyItem): unknown {
    const obj: any = {};
    if (message.op !== 0) {
      obj.op = modifyItem_OpToJSON(message.op);
    }
    if (message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.uid !== 0) {
      obj.uid = Math.round(message.uid);
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.flags !== 0) {
      obj.flags = Math.round(message.flags);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModifyItem>, I>>(base?: I): ModifyItem {
    return ModifyItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModifyItem>, I>>(object: I): ModifyItem {
    const message = createBaseModifyItem();
    message.op = object.op ?? 0;
    message.itemId = object.itemId ?? 0;
    message.uid = object.uid ?? 0;
    message.amount = object.amount ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.flags = object.flags ?? 0;
    return message;
  },
};

function createBaseEnterWorld(): EnterWorld {
  return { enterWorld: undefined, doorId: new Uint8Array(0) };
}

export const EnterWorld: MessageFns<EnterWorld> = {
  encode(message: EnterWorld, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enterWorld !== undefined) {
      World.encode(message.enterWorld, writer.uint32(10).fork()).join();
    }
    if (message.doorId.length !== 0) {
      writer.uint32(18).bytes(message.doorId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EnterWorld {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnterWorld();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.enterWorld = World.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.doorId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EnterWorld {
    return {
      enterWorld: isSet(object.enterWorld)
        ? World.fromJSON(object.enterWorld)
        : isSet(object.enter_world)
        ? World.fromJSON(object.enter_world)
        : undefined,
      doorId: isSet(object.doorId)
        ? bytesFromBase64(object.doorId)
        : isSet(object.door_id)
        ? bytesFromBase64(object.door_id)
        : new Uint8Array(0),
    };
  },

  toJSON(message: EnterWorld): unknown {
    const obj: any = {};
    if (message.enterWorld !== undefined) {
      obj.enterWorld = World.toJSON(message.enterWorld);
    }
    if (message.doorId.length !== 0) {
      obj.doorId = base64FromBytes(message.doorId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EnterWorld>, I>>(base?: I): EnterWorld {
    return EnterWorld.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EnterWorld>, I>>(object: I): EnterWorld {
    const message = createBaseEnterWorld();
    message.enterWorld = (object.enterWorld !== undefined && object.enterWorld !== null)
      ? World.fromPartial(object.enterWorld)
      : undefined;
    message.doorId = object.doorId ?? new Uint8Array(0);
    return message;
  },
};

function createBaseModifyInventory(): ModifyInventory {
  return { id: 0, toAdd: 0, isGhost: false };
}

export const ModifyInventory: MessageFns<ModifyInventory> = {
  encode(message: ModifyInventory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.toAdd !== 0) {
      writer.uint32(16).int32(message.toAdd);
    }
    if (message.isGhost !== false) {
      writer.uint32(24).bool(message.isGhost);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModifyInventory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModifyInventory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.toAdd = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isGhost = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModifyInventory {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      toAdd: isSet(object.toAdd)
        ? globalThis.Number(object.toAdd)
        : isSet(object.to_add)
        ? globalThis.Number(object.to_add)
        : 0,
      isGhost: isSet(object.isGhost)
        ? globalThis.Boolean(object.isGhost)
        : isSet(object.is_ghost)
        ? globalThis.Boolean(object.is_ghost)
        : false,
    };
  },

  toJSON(message: ModifyInventory): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.toAdd !== 0) {
      obj.toAdd = Math.round(message.toAdd);
    }
    if (message.isGhost !== false) {
      obj.isGhost = message.isGhost;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ModifyInventory>, I>>(base?: I): ModifyInventory {
    return ModifyInventory.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ModifyInventory>, I>>(object: I): ModifyInventory {
    const message = createBaseModifyInventory();
    message.id = object.id ?? 0;
    message.toAdd = object.toAdd ?? 0;
    message.isGhost = object.isGhost ?? false;
    return message;
  },
};

function createBasePlayerUpdate(): PlayerUpdate {
  return { netId: 0, x: 0, y: 0, state: 0 };
}

export const PlayerUpdate: MessageFns<PlayerUpdate> = {
  encode(message: PlayerUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.netId !== 0) {
      writer.uint32(8).uint32(message.netId);
    }
    if (message.x !== 0) {
      writer.uint32(21).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(29).float(message.y);
    }
    if (message.state !== 0) {
      writer.uint32(32).uint32(message.state);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.netId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.y = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.state = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerUpdate {
    return {
      netId: isSet(object.netId)
        ? globalThis.Number(object.netId)
        : isSet(object.net_id)
        ? globalThis.Number(object.net_id)
        : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      state: isSet(object.state) ? globalThis.Number(object.state) : 0,
    };
  },

  toJSON(message: PlayerUpdate): unknown {
    const obj: any = {};
    if (message.netId !== 0) {
      obj.netId = Math.round(message.netId);
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.state !== 0) {
      obj.state = Math.round(message.state);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerUpdate>, I>>(base?: I): PlayerUpdate {
    return PlayerUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerUpdate>, I>>(object: I): PlayerUpdate {
    const message = createBasePlayerUpdate();
    message.netId = object.netId ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.state = object.state ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
