// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: strkv.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "gtools.strkv.query";

export interface FindRow {
  method: FindRow_Method;
  key?: Uint8Array | undefined;
  index?: number | undefined;
}

export enum FindRow_Method {
  UNSPECIFIED = 0,
  KEY = 1,
  KEY_ANY = 2,
  INDEX = 3,
  UNRECOGNIZED = -1,
}

export function findRow_MethodFromJSON(object: any): FindRow_Method {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return FindRow_Method.UNSPECIFIED;
    case 1:
    case "KEY":
      return FindRow_Method.KEY;
    case 2:
    case "KEY_ANY":
      return FindRow_Method.KEY_ANY;
    case 3:
    case "INDEX":
      return FindRow_Method.INDEX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FindRow_Method.UNRECOGNIZED;
  }
}

export function findRow_MethodToJSON(object: FindRow_Method): string {
  switch (object) {
    case FindRow_Method.UNSPECIFIED:
      return "UNSPECIFIED";
    case FindRow_Method.KEY:
      return "KEY";
    case FindRow_Method.KEY_ANY:
      return "KEY_ANY";
    case FindRow_Method.INDEX:
      return "INDEX";
    case FindRow_Method.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FindCol {
  method: FindCol_Method;
  index: number;
}

export enum FindCol_Method {
  UNSPECIFIED = 0,
  ABSOLUTE = 1,
  RELATIVE = 2,
  UNRECOGNIZED = -1,
}

export function findCol_MethodFromJSON(object: any): FindCol_Method {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return FindCol_Method.UNSPECIFIED;
    case 1:
    case "ABSOLUTE":
      return FindCol_Method.ABSOLUTE;
    case 2:
    case "RELATIVE":
      return FindCol_Method.RELATIVE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FindCol_Method.UNRECOGNIZED;
  }
}

export function findCol_MethodToJSON(object: FindCol_Method): string {
  switch (object) {
    case FindCol_Method.UNSPECIFIED:
      return "UNSPECIFIED";
    case FindCol_Method.ABSOLUTE:
      return "ABSOLUTE";
    case FindCol_Method.RELATIVE:
      return "RELATIVE";
    case FindCol_Method.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Clause {
  row: FindRow | undefined;
  col?: FindCol | undefined;
}

export interface Query {
  where: Clause[];
}

function createBaseFindRow(): FindRow {
  return { method: 0, key: undefined, index: undefined };
}

export const FindRow: MessageFns<FindRow> = {
  encode(message: FindRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== 0) {
      writer.uint32(8).int32(message.method);
    }
    if (message.key !== undefined) {
      writer.uint32(18).bytes(message.key);
    }
    if (message.index !== undefined) {
      writer.uint32(32).int32(message.index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindRow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.method = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.index = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindRow {
    return {
      method: isSet(object.method) ? findRow_MethodFromJSON(object.method) : 0,
      key: isSet(object.key) ? bytesFromBase64(object.key) : undefined,
      index: isSet(object.index) ? globalThis.Number(object.index) : undefined,
    };
  },

  toJSON(message: FindRow): unknown {
    const obj: any = {};
    if (message.method !== 0) {
      obj.method = findRow_MethodToJSON(message.method);
    }
    if (message.key !== undefined) {
      obj.key = base64FromBytes(message.key);
    }
    if (message.index !== undefined) {
      obj.index = Math.round(message.index);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindRow>, I>>(base?: I): FindRow {
    return FindRow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindRow>, I>>(object: I): FindRow {
    const message = createBaseFindRow();
    message.method = object.method ?? 0;
    message.key = object.key ?? undefined;
    message.index = object.index ?? undefined;
    return message;
  },
};

function createBaseFindCol(): FindCol {
  return { method: 0, index: 0 };
}

export const FindCol: MessageFns<FindCol> = {
  encode(message: FindCol, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== 0) {
      writer.uint32(8).int32(message.method);
    }
    if (message.index !== 0) {
      writer.uint32(16).int32(message.index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindCol {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindCol();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.method = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.index = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindCol {
    return {
      method: isSet(object.method) ? findCol_MethodFromJSON(object.method) : 0,
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
    };
  },

  toJSON(message: FindCol): unknown {
    const obj: any = {};
    if (message.method !== 0) {
      obj.method = findCol_MethodToJSON(message.method);
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindCol>, I>>(base?: I): FindCol {
    return FindCol.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindCol>, I>>(object: I): FindCol {
    const message = createBaseFindCol();
    message.method = object.method ?? 0;
    message.index = object.index ?? 0;
    return message;
  },
};

function createBaseClause(): Clause {
  return { row: undefined, col: undefined };
}

export const Clause: MessageFns<Clause> = {
  encode(message: Clause, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.row !== undefined) {
      FindRow.encode(message.row, writer.uint32(10).fork()).join();
    }
    if (message.col !== undefined) {
      FindCol.encode(message.col, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Clause {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClause();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.row = FindRow.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.col = FindCol.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Clause {
    return {
      row: isSet(object.row) ? FindRow.fromJSON(object.row) : undefined,
      col: isSet(object.col) ? FindCol.fromJSON(object.col) : undefined,
    };
  },

  toJSON(message: Clause): unknown {
    const obj: any = {};
    if (message.row !== undefined) {
      obj.row = FindRow.toJSON(message.row);
    }
    if (message.col !== undefined) {
      obj.col = FindCol.toJSON(message.col);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Clause>, I>>(base?: I): Clause {
    return Clause.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Clause>, I>>(object: I): Clause {
    const message = createBaseClause();
    message.row = (object.row !== undefined && object.row !== null) ? FindRow.fromPartial(object.row) : undefined;
    message.col = (object.col !== undefined && object.col !== null) ? FindCol.fromPartial(object.col) : undefined;
    return message;
  },
};

function createBaseQuery(): Query {
  return { where: [] };
}

export const Query: MessageFns<Query> = {
  encode(message: Query, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.where) {
      Clause.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Query {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.where.push(Clause.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Query {
    return { where: globalThis.Array.isArray(object?.where) ? object.where.map((e: any) => Clause.fromJSON(e)) : [] };
  },

  toJSON(message: Query): unknown {
    const obj: any = {};
    if (message.where?.length) {
      obj.where = message.where.map((e) => Clause.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Query>, I>>(base?: I): Query {
    return Query.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Query>, I>>(object: I): Query {
    const message = createBaseQuery();
    message.where = object.where?.map((e) => Clause.fromPartial(e)) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
