// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: tank.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "gtools.tank.query";

export enum Field {
  TANK_FIELD_UNSPECIFIED = 0,
  TANK_FIELD_TYPE = 1,
  TANK_FIELD_OBJECT_TYPE = 2,
  TANK_FIELD_JUMP_COUNT = 3,
  TANK_FIELD_ANIMATION_TYPE = 4,
  TANK_FIELD_NET_ID = 5,
  TANK_FIELD_TARGET_NET_ID = 6,
  TANK_FIELD_FLAGS = 7,
  TANK_FIELD_FLOAT_VAR = 8,
  TANK_FIELD_VALUE = 9,
  TANK_FIELD_VECTOR_X = 10,
  TANK_FIELD_VECTOR_Y = 11,
  TANK_FIELD_VECTOR_X2 = 12,
  TANK_FIELD_VECTOR_Y2 = 13,
  TANK_FIELD_PARTICLE_ROTATION = 14,
  TANK_FIELD_INT_X = 15,
  TANK_FIELD_INT_Y = 16,
  TANK_FIELD_EXTENDED_LEN = 17,
  UNRECOGNIZED = -1,
}

export function fieldFromJSON(object: any): Field {
  switch (object) {
    case 0:
    case "TANK_FIELD_UNSPECIFIED":
      return Field.TANK_FIELD_UNSPECIFIED;
    case 1:
    case "TANK_FIELD_TYPE":
      return Field.TANK_FIELD_TYPE;
    case 2:
    case "TANK_FIELD_OBJECT_TYPE":
      return Field.TANK_FIELD_OBJECT_TYPE;
    case 3:
    case "TANK_FIELD_JUMP_COUNT":
      return Field.TANK_FIELD_JUMP_COUNT;
    case 4:
    case "TANK_FIELD_ANIMATION_TYPE":
      return Field.TANK_FIELD_ANIMATION_TYPE;
    case 5:
    case "TANK_FIELD_NET_ID":
      return Field.TANK_FIELD_NET_ID;
    case 6:
    case "TANK_FIELD_TARGET_NET_ID":
      return Field.TANK_FIELD_TARGET_NET_ID;
    case 7:
    case "TANK_FIELD_FLAGS":
      return Field.TANK_FIELD_FLAGS;
    case 8:
    case "TANK_FIELD_FLOAT_VAR":
      return Field.TANK_FIELD_FLOAT_VAR;
    case 9:
    case "TANK_FIELD_VALUE":
      return Field.TANK_FIELD_VALUE;
    case 10:
    case "TANK_FIELD_VECTOR_X":
      return Field.TANK_FIELD_VECTOR_X;
    case 11:
    case "TANK_FIELD_VECTOR_Y":
      return Field.TANK_FIELD_VECTOR_Y;
    case 12:
    case "TANK_FIELD_VECTOR_X2":
      return Field.TANK_FIELD_VECTOR_X2;
    case 13:
    case "TANK_FIELD_VECTOR_Y2":
      return Field.TANK_FIELD_VECTOR_Y2;
    case 14:
    case "TANK_FIELD_PARTICLE_ROTATION":
      return Field.TANK_FIELD_PARTICLE_ROTATION;
    case 15:
    case "TANK_FIELD_INT_X":
      return Field.TANK_FIELD_INT_X;
    case 16:
    case "TANK_FIELD_INT_Y":
      return Field.TANK_FIELD_INT_Y;
    case 17:
    case "TANK_FIELD_EXTENDED_LEN":
      return Field.TANK_FIELD_EXTENDED_LEN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Field.UNRECOGNIZED;
  }
}

export function fieldToJSON(object: Field): string {
  switch (object) {
    case Field.TANK_FIELD_UNSPECIFIED:
      return "TANK_FIELD_UNSPECIFIED";
    case Field.TANK_FIELD_TYPE:
      return "TANK_FIELD_TYPE";
    case Field.TANK_FIELD_OBJECT_TYPE:
      return "TANK_FIELD_OBJECT_TYPE";
    case Field.TANK_FIELD_JUMP_COUNT:
      return "TANK_FIELD_JUMP_COUNT";
    case Field.TANK_FIELD_ANIMATION_TYPE:
      return "TANK_FIELD_ANIMATION_TYPE";
    case Field.TANK_FIELD_NET_ID:
      return "TANK_FIELD_NET_ID";
    case Field.TANK_FIELD_TARGET_NET_ID:
      return "TANK_FIELD_TARGET_NET_ID";
    case Field.TANK_FIELD_FLAGS:
      return "TANK_FIELD_FLAGS";
    case Field.TANK_FIELD_FLOAT_VAR:
      return "TANK_FIELD_FLOAT_VAR";
    case Field.TANK_FIELD_VALUE:
      return "TANK_FIELD_VALUE";
    case Field.TANK_FIELD_VECTOR_X:
      return "TANK_FIELD_VECTOR_X";
    case Field.TANK_FIELD_VECTOR_Y:
      return "TANK_FIELD_VECTOR_Y";
    case Field.TANK_FIELD_VECTOR_X2:
      return "TANK_FIELD_VECTOR_X2";
    case Field.TANK_FIELD_VECTOR_Y2:
      return "TANK_FIELD_VECTOR_Y2";
    case Field.TANK_FIELD_PARTICLE_ROTATION:
      return "TANK_FIELD_PARTICLE_ROTATION";
    case Field.TANK_FIELD_INT_X:
      return "TANK_FIELD_INT_X";
    case Field.TANK_FIELD_INT_Y:
      return "TANK_FIELD_INT_Y";
    case Field.TANK_FIELD_EXTENDED_LEN:
      return "TANK_FIELD_EXTENDED_LEN";
    case Field.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** you need to do this shit because any doesnt work with enum */
export interface FieldValue {
  v: Field;
}

function createBaseFieldValue(): FieldValue {
  return { v: 0 };
}

export const FieldValue: MessageFns<FieldValue> = {
  encode(message: FieldValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.v !== 0) {
      writer.uint32(8).int32(message.v);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.v = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FieldValue {
    return { v: isSet(object.v) ? fieldFromJSON(object.v) : 0 };
  },

  toJSON(message: FieldValue): unknown {
    const obj: any = {};
    if (message.v !== 0) {
      obj.v = fieldToJSON(message.v);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FieldValue>, I>>(base?: I): FieldValue {
    return FieldValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FieldValue>, I>>(object: I): FieldValue {
    const message = createBaseFieldValue();
    message.v = object.v ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
