// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.1
// source: variant.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "gtools.variant.query";

export interface VariantClause {
  v: number;
}

export interface VariantQuery {
  where: VariantClause[];
}

function createBaseVariantClause(): VariantClause {
  return { v: 0 };
}

export const VariantClause: MessageFns<VariantClause> = {
  encode(message: VariantClause, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.v !== 0) {
      writer.uint32(8).uint32(message.v);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariantClause {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariantClause();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.v = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VariantClause {
    return { v: isSet(object.v) ? globalThis.Number(object.v) : 0 };
  },

  toJSON(message: VariantClause): unknown {
    const obj: any = {};
    if (message.v !== 0) {
      obj.v = Math.round(message.v);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VariantClause>, I>>(base?: I): VariantClause {
    return VariantClause.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VariantClause>, I>>(object: I): VariantClause {
    const message = createBaseVariantClause();
    message.v = object.v ?? 0;
    return message;
  },
};

function createBaseVariantQuery(): VariantQuery {
  return { where: [] };
}

export const VariantQuery: MessageFns<VariantQuery> = {
  encode(message: VariantQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.where) {
      VariantClause.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariantQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariantQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.where.push(VariantClause.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VariantQuery {
    return {
      where: globalThis.Array.isArray(object?.where) ? object.where.map((e: any) => VariantClause.fromJSON(e)) : [],
    };
  },

  toJSON(message: VariantQuery): unknown {
    const obj: any = {};
    if (message.where?.length) {
      obj.where = message.where.map((e) => VariantClause.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VariantQuery>, I>>(base?: I): VariantQuery {
    return VariantQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VariantQuery>, I>>(object: I): VariantQuery {
    const message = createBaseVariantQuery();
    message.where = object.where?.map((e) => VariantClause.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
